### ISSUE TITLE
User-index ordering Heisenbug.

### ISSUE THREAD

**Issue by jdickey** [jdickey/new_poc#250]
A bit of investigation of the [(now-)repeatably-failing spec](https://github.com/jdickey/new_poc/blob/fb5eae1/spec/controllers/users_controller_spec.rb#L54-L68) for `UsersController`'s 'index' action shows that, as of Line [56](https://github.com/jdickey/new_poc/blob/fb5eae1/spec/controllers/users_controller_spec.rb#L56) of `users_controller_spec.rb`, `users` (the array initialised in the [`before :each` block](https://github.com/jdickey/new_poc/blob/fb5eae1/spec/controllers/users_controller_spec.rb#L41) for the spec) and `index_users` (which is loaded from the [`index` action](https://github.com/jdickey/new_poc/blob/fb5eae1/app/controllers/users_controller/action/index.rb#L16), getting its data from the [`UserRepository#all` method](https://github.com/jdickey/new_poc/blob/fb5eae1cb6ca8d62a54365e233e8893fa9550e48/app/repositories/user_repository.rb#L13)), have the same *data* but in a different *order*.

See [this comment on PR #247](https://github.com/jdickey/new_poc/pull/247#issuecomment-82306560) for more background discussion.

#### Exploration

Setting a breakpoint at line 56 of `users_controller_spec.rb` allows us to see that the sequence of user names in `users`, which are each of the pattern "J Random User Number *n*", has values of *n* in the sequence *29, 30, 31, 32, 33*; the sequence in `index_users` at that point is *33, 29, 30, 31, 32*. At first I thought that perhaps the filtering done in [`UserRepository#all`](https://github.com/jdickey/new_poc/blob/fb5eae1/app/repositories/user_repository.rb#L13) might have skewed the ordering. However, adding a breakpoint there and accessing the database directly (via `UserDao.all` yielded the second sequence. This strongly suggests that the fault somehow lies at [the point](https://github.com/jdickey/new_poc/blob/fb5eae1/spec/controllers/users_controller_spec.rb#L40-L41) where we first instruct the DAO to add a record matching an entity to storage and then add that entity to an internal list. It seems likely that *this* is caused by some internal caching within the database driver and/or an interaction amongst the various moving parts used for data persistence in the test environment.

#### An Obvious and Expedient Fix?

So what to do? Our `UserRepository#all` method is already [filtering out](https://github.com/jdickey/new_poc/blob/fb5eae1/app/repositories/user_repository.rb#L13) the Guest User from the returned results; perhaps the most expedient fix is to change that method so that it also sorts the results by slug?

#### No, Let's Focus More Tightly

Should that ordering be at the repository level or at the index-action level? After thinking about it, I'd argue for the action level; at present, this is the only User action that cares about ordering of multiple records.

**Comment by jdickey** [comment]
And it resurfaced again, in Commit a6d2aaa. Is this a regression, or was our earlier declaration of defect death premature? Reopening.

**Comment by jdickey** [comment]
Heisenbug appearance [13 April 2015 at 00.09](https://codeship.com/projects/48457/builds/5043321)

Seed 36205. Reproducible when forcing that seed on dev system, as of Commit 2ef76af.

```
Failures:

1) UsersController GET 'index' assigns the non-Guest users to the :users item
Failure/Error: expect(index_user[attrib]).to eq user[attrib]
  
  expected: "jruser108@example.com"
       got: "jruser111@example.com"
  
  (compared using ==)
# ./spec/controllers/users_controller_spec.rb:65:in `block (5 levels) in <top (required)>'
# ./spec/controllers/users_controller_spec.rb:64:in `each'
# ./spec/controllers/users_controller_spec.rb:64:in `block (4 levels) in <top (required)>'
# ./spec/controllers/users_controller_spec.rb:62:in `each'
# ./spec/controllers/users_controller_spec.rb:62:in `each_with_index'
# ./spec/controllers/users_controller_spec.rb:62:in `block (3 levels) in <top (required)>'
```

**Comment by jdickey** [comment]
Heisenbug appearance [18 April 2015 at 17:08](https://codeship.com/projects/48457/builds/5170148)

Seed 31536. **Not** reproducible when forcing that seed on dev system, as of Commit 3df52ad.

Re-running with randomised seed (`2832`) yields green bar.

**Comment by jdickey** [comment]
Heisenbug appearance [24 April 2015 at 00:48](https://codeship.com/projects/48457/builds/5269791)

Seed 6976. Not reproducible when forcing that seed on dev system, as of Commit f07c49d.

Re-running with randomised seed (1258) yields green bar.

```
Failures:

1) Member can publish articles and view it on the landing page
Failure/Error: expect(caption.native.to_html).to eq format(caption_str, index + 1)
  
  expected: "<figcaption><p>This is <em>another</em> post body. (Number 1 in a series.)</p></figcaption>"
       got: "<figcaption><p>This is <em>another</em> post body. (Number 2 in a series.)</p></figcaption>"
  
  (compared using ==)
# ./spec/features/member_can_publish_article_view_on_landing_page_spec.rb:25:in `block (3 levels) in <top (required)>'
# ./spec/features/member_can_publish_article_view_on_landing_page_spec.rb:24:in `each'
# ./spec/features/member_can_publish_article_view_on_landing_page_spec.rb:24:in `each_with_index'
# ./spec/features/member_can_publish_article_view_on_landing_page_spec.rb:24:in `block (2 levels) in <top (required)>'
```

**Comment by jdickey** [comment]
Heisenbug appearance [24 April 2015 at 17:15](https://codeship.com/projects/48457/builds/5284456)

Seed 20184. Reproducible when forcing that seed on dev system, as of Commit 97daf18.

Re-running with randomised seed (10156) yields green bar.

**Comment by jdickey** [comment]
Heisenbug appearance 27 April at 03:15

Seed 42929. Reproducible when forcing that seed on dev system, as of Commit ddfc8ef.

```
Failures:

  1) UsersController GET 'index' assigns the non-Guest users to the :users item
     Failure/Error: expect(index_user[attrib]).to eq user[attrib]
       
       expected: "jruser96@example.com"
            got: "jruser100@example.com"
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:65:in `block (5 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:64:in `each'
     # ./spec/controllers/users_controller_spec.rb:64:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:62:in `each'
     # ./spec/controllers/users_controller_spec.rb:62:in `each_with_index'
     # ./spec/controllers/users_controller_spec.rb:62:in `block (3 levels) in <top (required)>'
```

**Comment by jdickey** [comment]
Heisenbug appearance 15 May at 15:49.

Seed 59042. Not reproducible when forcing that seed on dev system, as of Commit c828208.

```
Failures:

1) PostsController GET 'index' for the guest user assigns only the public posts to :posts
Failure/Error: expect(post).to be_saved_post_entity_for public_posts[index]
  Expected a source and target(post-save) entity to have the same author name, body, image_url, pubdate, slug and title
   fields, but slug fields do not match: got test-title-number-384 but expected test-title-number-381; and title fields do not match: got Test Title Number 384 but expected Test Title Number 381
# ./spec/controllers/posts_controller_spec.rb:82:in `block (5 levels) in <top (required)>'
# ./spec/controllers/posts_controller_spec.rb:81:in `each'
# ./spec/controllers/posts_controller_spec.rb:81:in `each_with_index'
# ./spec/controllers/posts_controller_spec.rb:81:in `block (4 levels) in <top (required)>'
```

**Comment by jdickey** [comment]
Heisenbug appearance 29 May at 02:39.

Seed 34871. Reproducible when forcing that seed on dev system, as of Commit d29d1a8.

```
Failures:

  1) UsersController GET 'index' assigns the non-Guest users to the :users item
     Failure/Error: expect(index_user[attrib]).to eq user[attrib]
       
       expected: "jruser110@example.com"
            got: "jruser111@example.com"
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:65:in `block (5 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:64:in `each'
     # ./spec/controllers/users_controller_spec.rb:64:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:62:in `each'
     # ./spec/controllers/users_controller_spec.rb:62:in `each_with_index'
     # ./spec/controllers/users_controller_spec.rb:62:in `block (3 levels) in <top (required)>'
```

**Comment by jdickey** [comment]
Heisenbug appearance 9 June at 01:40.

Seed 10427. Reproducible when forcing that seed on dev systgem, as of Commit 8327757.

```
Failures:

  1) ApplicationHelper::BuildMenuFor build_menu_for for a Registered User behaves like a valid menu for a Registered User, of a specified style behaves like a menu containing appropriate items for a Registered User when called passing in :sidebar for a Registered User contains a top-level `ul` element that has as its third child element an `li` element which serves as a vertical spacer
     Failure/Error: it_behaves_like_a_menu_separator index: 2,
       
       expected true
            got false
     Shared Example Group: "a menu containing appropriate items for a Registered User" called from ./spec/support/shared_examples/helpers/valid_menu_for_registered_user.rb:15
     Shared Example Group: "a valid menu for a Registered User, of a specified style" called from ./spec/helpers/application_helper/build_menu_for_spec.rb:24
     # ./spec/support/shared_examples/helpers/menu_spec_helper_functions.rb:137:in `it_behaves_like_a_menu_separator'
     # ./spec/support/shared_examples/helpers/registered_user_menu_items.rb:38:in `block (4 levels) in <top (required)>'

  2) ApplicationHelper::BuildMenuFor build_menu_for for a Registered User behaves like a valid menu for a Registered User, of a specified style behaves like a menu containing appropriate items for a Registered User when called passing in :sidebar for a Registered User contains a top-level `ul` element that has as its seventh child element an `li` element which serves as a vertical spacer
     Failure/Error: it_behaves_like_a_menu_separator index: 6,
       
       expected true
            got false
     Shared Example Group: "a menu containing appropriate items for a Registered User" called from ./spec/support/shared_examples/helpers/valid_menu_for_registered_user.rb:15
     Shared Example Group: "a valid menu for a Registered User, of a specified style" called from ./spec/helpers/application_helper/build_menu_for_spec.rb:24
     # ./spec/support/shared_examples/helpers/menu_spec_helper_functions.rb:137:in `it_behaves_like_a_menu_separator'
     # ./spec/support/shared_examples/helpers/registered_user_menu_items.rb:71:in `block (4 levels) in <top (required)>'

  3) ApplicationHelper::BuildMenuFor build_menu_for for a Registered User behaves like a valid menu for a Registered User, of a specified style behaves like a menu containing appropriate items for a Registered User when called passing in :sidebar for a Registered User contains a top-level `ul` element that has as its fifth child element an `li` element which serves as a vertical spacer
     Failure/Error: it_behaves_like_a_menu_separator index: 4,
       
       expected true
            got false
     Shared Example Group: "a menu containing appropriate items for a Registered User" called from ./spec/support/shared_examples/helpers/valid_menu_for_registered_user.rb:15
     Shared Example Group: "a valid menu for a Registered User, of a specified style" called from ./spec/helpers/application_helper/build_menu_for_spec.rb:24
     # ./spec/support/shared_examples/helpers/menu_spec_helper_functions.rb:137:in `it_behaves_like_a_menu_separator'
     # ./spec/support/shared_examples/helpers/registered_user_menu_items.rb:54:in `block (4 levels) in <top (required)>'

Finished in 21.34 seconds (files took 4.08 seconds to load)
1137 examples, 3 failures

Failed examples:

rspec ./spec/helpers/application_helper/build_menu_for_spec.rb:24 # ApplicationHelper::BuildMenuFor build_menu_for for a Registered User behaves like a valid menu for a Registered User, of a specified style behaves like a menu containing appropriate items for a Registered User when called passing in :sidebar for a Registered User contains a top-level `ul` element that has as its third child element an `li` element which serves as a vertical spacer
rspec ./spec/helpers/application_helper/build_menu_for_spec.rb:24 # ApplicationHelper::BuildMenuFor build_menu_for for a Registered User behaves like a valid menu for a Registered User, of a specified style behaves like a menu containing appropriate items for a Registered User when called passing in :sidebar for a Registered User contains a top-level `ul` element that has as its seventh child element an `li` element which serves as a vertical spacer
rspec ./spec/helpers/application_helper/build_menu_for_spec.rb:24 # ApplicationHelper::BuildMenuFor build_menu_for for a Registered User behaves like a valid menu for a Registered User, of a specified style behaves like a menu containing appropriate items for a Registered User when called passing in :sidebar for a Registered User contains a top-level `ul` element that has as its fifth child element an `li` element which serves as a vertical spacer
```

**Comment by jdickey** [comment]
Heisenbug appearance Tuesday 7 July at 14:48

Seed 46437. Reproducible when forcing that seed on dev system, as of Commit e562878.

```
Failures:

  1) UsersController GET 'index' assigns the non-Guest users to the :users item
     Failure/Error: expect(index_user[attrib]).to eq user[attrib]
       
       expected: "jruser107@example.com"
            got: "jruser109@example.com"
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:65:in `block (5 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:64:in `each'
     # ./spec/controllers/users_controller_spec.rb:64:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:62:in `each'
     # ./spec/controllers/users_controller_spec.rb:62:in `each_with_index'
     # ./spec/controllers/users_controller_spec.rb:62:in `block (3 levels) in <top (required)>'
```
